name: mc_crud_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  go_router: ^6.0.3
  equatable: ^2.0.5
  injectable: ^2.1.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  flutter_screenutil: ^5.6.1
  freezed_annotation: ^2.2.0
  flutter_staggered_animations: ^1.1.1

  # NOTICE : this package written by me (Ali Hoseinpoor)
  hero_button:
    git:
      url: https://gitlab.com/Ali_h/hero-button.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo/
    - assets/image/icon/
